# Generated by Django 6.0.1 on 2026-01-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_h5p', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='h5pgrade',
            unique_together=set(),
        ),
    ]
